trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- script: docker pull giginet/gbdk
  displayName: 'Pull Docker image'

- script: docker run --rm -v `pwd`:/gbdk giginet/gbdk /opt/gbdk/bin/lcc -o /gbdk/rom.gb /gbdk/game.c
  displayName: 'Build ROM'
- task: GitHubRelease@0
  inputs:
    gitHubConnection: 'giginet'
    repositoryName: '$(Build.Repository.Name)'
    action: 'create'
    target: '$(Build.SourceVersion)'
    tagSource: 'auto'
    title: '$(Build.SourceVersion)'
    releaseNotesSource: 'input'
    releaseNotes: 'Beta'
    assets: '*.gb'
    isDraft: true
    addChangeLog: false