trigger:
- task: GitHubRelease@0
  inputs:
    repositoryName: '$(Build.Repository.Name)'
    action: 'create'
    target: '$(Build.SourceVersion)'
    tagSource: 'auto'
    releaseNotesSource: 'input'
    releaseNotes: 'Beta'
    assets: '$(Build.ArtifactStagingDirectory)/*.gb'
    isPreRelease: true
    addChangeLog: false
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- script: docker pull giginet/gbdk
  displayName: 'Pull Docker image'

- script: docker run --rm -v `pwd`:/gbdk giginet/gbdk /opt/gbdk/bin/lcc -o /gbdk/rom.gb /gbdk/game.c
  displayName: 'Build ROM'

- task: GitHubRelease@0
  displayName: 'Upload to GitHub'
